# Generated by Django 4.0.2 on 2022-02-18 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegCode',
        ),
    ]
